# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_firstAssignment_login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_firstAssignment_login

  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.0'
end
